server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    # 整合 nacos
    nacos:
      discovery:
        # 指定 nacos server 地址
        server-addr: 39.102.66.189:8848
    gateway:
      discovery:
        locator:
          # 让 gateway 通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: timebetween_route
          uri: lb://user-center
          predicates:
            # 符合时间范围，才会转发到用户微服务
            - TimeBetween=上午0:00,下午11:59
          filters:
            # 为原始请求添加名为 X-Request-Foo ，值为 Bar 的请求头
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a,b

# 服务健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 展示详情
      show-details: always